package com.example.entity

interface FilmApiInterface {
    val kinopoiskId: Int
    val kinopoiskHDId: String
    val imdbId: String?
    val nameRu: String?
    val nameEn: String?
    val nameOriginal: String?
    val posterUrl: String?
    val posterUrlPreview: String
    val coverUrl: String
    val logoUrl: String
    val reviewsCount: Int
    val ratingGoodReview: Double
    val ratingGoodReviewVoteCount: Int
    val ratingKinopoisk: Double?
    val ratingKinopoiskVoteCount: Int
    val ratingImdb: Double?
    val ratingImdbVoteCount: Int
    val ratingFilmCritics: Double
    val ratingFilmCriticsVoteCount: Int
    val ratingAwait: String?
    val ratingAwaitCount: Int
    val ratingRfCritics: String?
    val ratingRfCriticsVoteCount: String?
    val webUrl: String
    val year: Int
    val filmLength: Int
    val slogan: String
    val description: String?
    val shortDescription: String?
    val editorAnnotation: String?
    val isTicketsAvailable: Boolean
    val productionStatus: String?
    val type: String
    val ratingMpaa: String
    val ratingAgeLimits: String
    val countries: List<Country>
    val genres: List<Genre>
    val startYear: String?
    val endYear: String?
    val serial: Boolean
    val shortFilm: Boolean
    val completed: Boolean
    val hasImax: Boolean
    val has3D: Boolean
    val lastSync: String
}